### ISSUE TITLE
Something wrong with installation on mac

### ISSUE THREAD

**Issue by haik** [samee/obliv-c#29]
I don't know if anyone has tried to install the obliv-c on Mac. I encounter the following problem:
```
/usr/include/string.h[131:87-93] : syntax error
Parsing errorFatal error: exception Frontc.ParseError("Parse error")
ar cr _build/libobliv.a _build/obliv_bits.o _build/ot.o _build/dualex.o _build/atomic_queue.o _build/commitReveal.o _build/obliv_network_utils.o _build/bcrandom.o _build/privacy-free.o _build/psi.o _build/nnob.o _build/copy.o _build/copy.oo
ar: _build/copy.oo: No such file or directory
make: *** [_build/libobliv.a] Error 1
```
Then make stopped. Who can help me with this problem?

**Comment by samee** [comment]
Yes, this is the usual problem people unfortunately face when installing on a Mac. The problem is that standard C headers in Mac uses non-standard directives that CIL does not parse correctly. Our usual recommendation is to use it in a Linux VM. That said, maybe @jackdoerner has a better answer, since he was trying to port it to Macs recently.

**Comment by jackdoerner** [comment]
Hello there,

I can confirm, obliv-c does indeed work on Mac OS. Or, to be more specific, it works on exactly one instance of Mac OS so far, which is mine. Bringing the count up to two is a step in the right direction, though. Unfortunately, there are some hoops you have to jump through, the primary one being that you need a copy of the real GCC (and the real GCC's `cpp`), rather than llvm, which is what Apple ships. I got mine from [macports](www.macports.org). In addition, you'll need all of obliv-c's regular dependencies, installed in such a way that the linker can find them. These should all be available via macports (and probably also via homebrew/fink).

Once you have a working copy of gcc and all the dependencies, you should be able to build obliv-c like this:
`CC=<path_to_real_gcc> CPP=<path_to_real_gcc's_cpp> ./configure && make`

Let me know if that works for you, and where you run into trouble, if you do. This process is far from official, so it's certainly possible I've missed something.

UPDATE:
The README now includes instructions for Mac OS, which I verified by following them on a fresh installation of Sierra. If you have any issue with these instructions, let me know.

**Comment by samee** [comment]
Closing this as a stale issue. Please reopen if problem persists.
