### ISSUE TITLE
Building on Mac OSX

### ISSUE THREAD

**Issue by evansuva** [samee/obliv-c#36]
I'm trying to build on Mac OSX, following the instructions in http://oblivc.org/tutorial/ (which I believe are the same as the README now).  I get this error:

    make: *** No rule to make target `_build/obliv_bits.o', needed by `_build/libobliv.a'.  Stop.

Looks like things worked okay until that.

**Comment by jackdoerner** [comment]
Hmm. That's a very odd error to get. Perhaps you can paste the full build output somewhere? I suspect there is some other root cause.

**Comment by evansuva** [comment]
Thanks, Jack! Here's the full output:

[output.txt](https://github.com/samee/obliv-c/files/1132068/output.txt)

**Comment by jackdoerner** [comment]
Interesting. The difference between your build and mine, as far as I can tell:
1. I am using macports' version of ginstall (coreutils) and perl, whereas you're using apple's.
2. Your copies of Xcode's utilities seem to live in a different place than mine, which is odd.

I have three lines in my build log that are absent from yours, and seem to be relevant (given with one line of context before and after):
```
cd lib/perl5; perl Makefile.PL INSTALL_BASE="/usr/local"
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for cilly
```

Best guess so far: you're using a different (older?) version of Xcode, which has some oddness that causes the makefile not to be generated correctly. Second best guess: you need macports' version of perl. I'm leaning toward the former option because some folks here have installed obliv-c successfully without macports' perl. I would check for updated versions of Xcode, and if there is not one, try installing macports' perl. If neither of those things works, we can dig deeper.

**Comment by evansuva** [comment]
Thanks, Jack - there was definitely something wrong with my Xcode install. I've installed the latest Xcode and get past this problem now. (Running into something else, but will start a new issue if I can't figure this one out myself.)

**Comment by jackdoerner** [comment]
Excellent. If your further issue is related to the instructions (as opposed to being unique to your own system), be sure to notify.
