### ISSUE TITLE
Passing obliv ints in a struct- Doesn't seem to work

### ISSUE THREAD

**Issue by danxinnoble** [samee/obliv-c#45]
I would like to pass structs to the .oc program. The structs contain obliv int fields. Is this possible?

The way I have been trying to do it is to just use feedOblivInt on the int field on the struct, eg:
> obliv int v1x = feedOblivInt(io->input.x, 1);

but this does not work. I get the following error message:
> Error: dotProd.oc:10:cannot convert obliv type to non-obliv
> Fatal error: exception Errormsg.Error

Am I doing something wrong or is it not possible to do this in obliv-c?

I've attached a basic test program in which the struct is a vector with two obliv int components and the program attempts to compute the dot-product. To run make you need to unzip common.zip and dotProd.zip into the same parent dir. (The Makefile etc follow the same patterns as in the test programs of obliv-c.)

[common.zip](https://github.com/samee/obliv-c/files/1352672/common.zip)
[dotProd.zip](https://github.com/samee/obliv-c/files/1352667/dotProd.zip)

**Comment by samee** [comment]
The way to think about feedOblivInt is that it takes in a local, native, int as input and converts it into an obliv int. Ordinary ints are stored in local memory, while obliv ints need state shared across both machines.

So in dotProd.h, you want to have ordinary ints in struct vector. These will be populated in main(), which is good since a plain C file cannot access obliv int anyway. Feed will convert them into obliv int, do the math, and finally convert the result back using revealOblivInt (not ocBroadcastInt, which is used for exchanging plaintext data). 

I'll recommend starting with the tutorial in http://oblivc.org. Another good reference is just the [obliv.oh](https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv.oh) header file, where you can see that the feedOblivInt function takes in a normal int and returns obliv int, while revealOblivInt goes the other way.

Hope this helps.
