### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by freelyyu** [samee/obliv-c#74]
Does the Yao's protocol  utilize garbled circuit optimization techniques such as free XOR 、pipelined circuit execution and other techniques

**Comment by weikengchen** [comment]
*Theoretically,* Yao's protocol is an algorithm that integrates oblivious transfer + garbled circuits for secure two-party computation.

So, this protocol doesn't rely on a specific garbling scheme. Any garbling scheme with a standard syntax can serve as an ingredient of Yao's protocol.

---

I think you are referring about this repo's implementation.

Its instantiation of Yao protocol does involve free XOR-style technique, named Half Gate,
as https://github.com/samee/obliv-c/blob/obliv-c/src/ext/oblivc/obliv_bits.c#L1057 shows.

---

For your question on pipelined circuits, I assume you are referring to the pipelined circuit evaluation mentioned in https://www.cs.umd.edu/~jkatz/papers/usenix2011.pdf.

Since Obliv-C is inherently a reactive two-party computation platform, I think it is inherently pipelined. 

---

*Tip:* don't use "some question" as the title of an issue. Make it not too long, not too short, and specific as possible. There is actually some "techniques" and "subtleties" in the titles. 

If you are interested, you can read Oded Goldreich's paper, Section 4.1.
http://www.wisdom.weizmann.ac.il/~oded/R2/re-writing.pdf

**Comment by freelyyu** [comment]
OK，thanks a lot for your help and patience.I  am sorry that  I did not express my question clearly,actually,I wonder know whether  Yao's protocol of obliv-c utilize  halfgate 、pipelined circuit execution or not, according to your letter,I almost know the answer ,it utilizes halfgate and it is inherently pipelined. I would like to read  Oded Goldreich's paper --how to wirte a paper.
